name: Run Discord Bot

on:
  workflow_dispatch:  # Allows manual triggering
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Download previous settings if they exist
      - name: Download settings
        uses: actions/download-artifact@v2
        with:
          name: bot-settings
          path: ./
        continue-on-error: true  # Don't fail if no previous settings exist

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Discord bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          touch bot_log.txt  # Ensure log file exists
          python bot.py
        timeout-minutes: 350  # GitHub Actions has a 6-hour (360 minute) limit

      # Save settings for next run
      - name: Upload settings
        if: always()  # Upload even if the bot crashes
        uses: actions/upload-artifact@v2
        with:
          name: bot-settings
          path: settings.json
          retention-days: 1  # Only need to keep until next run

      # Upload logs
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: bot-logs
          path: bot_log.txt
          retention-days: 7
